### ISSUE TITLE
Piperator is not getting installed on Blender 2.90 alpha

### ISSUE THREAD

**Issue by raindropsfromsky** [lautis/piperator#12]
I am using Blender 2.90 alpha on Windows 10 Home, 64 bit.
I am unable to install the Piperator addon.
When I go through the steps of installation, nothing happens. There is no error message also.

**Comment by tristandruyen** [comment]
@raindropsfromsky 

This is not the repo you're looking for.
This is not for the blender addon, but for a ruby library used by coders.

**Comment by lautis** [comment]
Unfortunately can't help with this. As mentioned, the Blender add-on is an unrelated project with the same name.
